### ISSUE TITLE
Grafana UI の `.js` ファイルのキャッシュがたまに壊れて閲覧不能になる

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/seichi_infra#1094]
## 概要

問題が発生したときは、単一の JS ファイル [`https://grafana.onp-k8s.admin.seichi.click/public/build/7490.cf2da2a42f577bdb1843.js`](https://grafana.onp-k8s.admin.seichi.click/public/build/7490.cf2da2a42f577bdb1843.js) に Syntax Error があると言われロードできなくなる。当該パスのキャッシュをクリアすると即時に、またはしばらく時間を置く (cache TTL 分待つ？) と問題が解消する。

@kory33 と @lis2a の環境で発生した。

## 当分の対応

Terraform から [`https://grafana.onp-k8s.admin.seichi.click/public/build/7490.cf2da2a42f577bdb1843.js`](https://grafana.onp-k8s.admin.seichi.click/public/build/7490.cf2da2a42f577bdb1843.js) のみキャッシュを切るということも考えたが、原因がわかっていないまま謎のルールを追加したくないので、まずは原因特定を試みたい。

次に問題が発生したとき、壊れているときと壊れていないときにどのような差分が存在するのかなどを調べたい。

**Comment by lis2a** [comment]
普通に壊れてくれた (ありがとう〜)
私の環境ではWindowsだけ普通なのにmacOSだけこうなる (そうはならんやろ)
<img width="1538" alt="CleanShot 2023-06-20 at 16 20 54@2x" src="https://github.com/GiganticMinecraft/seichi_infra/assets/82575685/271e4336-f6ae-47f4-99ac-dd8f79c3d3a6">

発生時の`7490.cf2da2a42f577bdb1843.js`
https://gist.github.com/lis2a/40e7844c2e4d9280f3007f96d330d659

**Comment by lis2a** [comment]
NextDNS を Disable にしてブラウザのキャッシュを削ぎ落としても直らなかった
<img width="1001" alt="CleanShot 2023-06-20 at 16 28 04@2x" src="https://github.com/GiganticMinecraft/seichi_infra/assets/82575685/ad39964f-9423-4dc8-8cbb-69435321fef1">

**Comment by kory33** [comment]
@lis2a  報告助かります！

とりあえず cache purge 前後で壊れているファイルの内容を取ってみました
https://gist.github.com/kory33/a4c4e701b87f38f2dfab77b31b0e8b66

**Comment by kory33** [comment]
原因分かった

該当箇所の差分は次のような感じで

```diff
- var i=t(77205),u=0,s=Math.random(),f=i(1 .toString);
+ var i=t(77205),u=0,s=Math.random(),f=i(1.toString);
```

[Cloudflare Auto Minify](https://developers.cloudflare.com/support/speed/optimization-file-size/using-cloudflare-auto-minify/) が誤ってスペースを消しちゃってた模様。このバグはすでに Cloudflare Community には[報告](https://community.cloudflare.com/t/auto-minify-breaks-javascript-syntax/417399)されていますが、まだ修正されてないぽい (報告すべきっぽい)。

Auto Minify を JS について全面的に切る方向性で対応します。

**Comment by lis2a** [comment]
やっぱり Auto Minify だったか...
原因わかってよかったです、原因解明お疲れ様です
