### ISSUE TITLE
proxy-kubernetes上でvotelistener用のservice-endpointを公開する

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#27]
related: #18 [#9d4964d](https://github.com/GiganticMinecraft/seichi_infra/pull/18/commits/9d4964da6adb887fd1db8d56d21a44a23f4f88d0)

**Comment by unchama** [comment]
ちなみにTCPShield君はL7レベルまで読んでマイクラサーバーの通信であることを確認していて、WAFならぬMAF(Minecraft Application Firewall)みたいな感じになってるっぽいのでマイクラ以外の通信を通すのは厳しそう
※MAFは今作った造語

**Comment by mamireimu** [comment]
メンションされたので確認しました。合ってます。

**Comment by unchama** [comment]
> メンションされたので確認しました。合ってます。

@mamireimu 回答ありがとうございます！！！！謎技術！！！！

**Comment by kory33** [comment]
関係ないnanodeインスタンスを置いてもいいかも。正直どちらでも良さそうな感じはある

**Comment by unchama** [comment]
- k8s(loadbalancer)で +$10/month
- nanodeで +$5/month

**Comment by kory33** [comment]
別loadbalancer建てるくらいならnanodeを置くか既存のLB配下に置いた方が良さそうな感じがある

**Comment by unchama** [comment]
そうか　例えばprod-bungeeのloadbalancerに同居させればタダだな

**Comment by unchama** [comment]
> そうか　例えばprod-bungeeのloadbalancerに同居させればタダだな

これは以下の理由からできない：
1. k8sのserviceオブジェクトの仕様として、複数のPodをEndpointに指定することはできない
2. prod-bungee用のloadbalancerはproxy-protocol v2オプションが入ってるのでそもそも1.ができたとしても繋がらない

https://github.com/GiganticMinecraft/seichi_infra/blob/308e27d100ab93b4ab698ce5e3fe661d88abdf6e/proxy-kubernetes/production-k8s-manifests/bungeecord-service.yaml#L11
