### ISSUE TITLE
docker-ce-and-compose.shが環境によってこける

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#28]
https://github.com/GiganticMinecraft/seichi_infra/blob/32f6b7292682e0ef59bacb39463cd6527c7049dc/util-scripts/setup/docker-ce-and-compose.sh#L34
コイツは存在しないことも想定されるので行末に` || true`を追加すべき

**Comment by kory33** [comment]
そうっぽい
