### ISSUE TITLE
`seichi-onp-network-iap`でcloudflared認証情報を永続化する

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#32]
現状docker comoose downなどが走ると消える
関連: #18

**Comment by kory33** [comment]
これマジ？してるはず…

https://github.com/GiganticMinecraft/seichi_infra/blob/8d1eace491c66bbf31f781d2b7390fb5a4791ba8/seichi-onp-network-iap/services/docker-compose.yml#L8

**Comment by unchama** [comment]
わたしは完全に見逃していました　の顔をしながらそっ閉じします
