### ISSUE TITLE
cloudflared-with-auto-dns-routeの新しいバージョンがリリースされたらrenovate-botにversion bumpさせるpullreqを作ってもらう

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#33]
https://github.com/GiganticMinecraft/seichi_infra/blob/8d1eace491c66bbf31f781d2b7390fb5a4791ba8/seichi-onp-network-iap/services/docker-compose.yml#L6
これとか

関連: #18

**Comment by kory33** [comment]
実はRenovateはこれを認識していて(#228 参照)、このイメージのタグがsemverとかじゃないからPR出してないだけっぽい

**Comment by kory33** [comment]
renovate configかタグ付けのどちらかを直したい

**Comment by kory33** [comment]
Helmのところ：

**Comment by kory33** [comment]
Helm Chart 内での参照

https://github.com/GiganticMinecraft/seichi_infra/blob/4e9d04c54cf1b53d32a31bcd6224c92922b55ac0/helm-charts/cloudflared-tunnel/templates/deployment.yaml#L26

と、`cloudflared-k8s-endpoint.yaml` 内での参照

https://github.com/GiganticMinecraft/seichi_infra/blob/4e9d04c54cf1b53d32a31bcd6224c92922b55ac0/seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/cloudflared-k8s-endpoint/cloudflared-k8s-endpoint.yaml#L50

だけなんで、これらを認識するように renovate に指示する必要があり、結局 renovate config を書く必要がある

**Comment by kory33** [comment]
> 実はRenovateはこれを認識していて(#228 参照)、このイメージのタグがsemverとかじゃないからPR出してないだけっぽい

これは outdated なコメントで、現状は認識されていないです。実際bumpされるのかとかは https://github.com/GiganticMinecraft/seichi_infra/issues/432 の後に考えます。まずは認識させるところからやります。

**Comment by kory33** [comment]
`allowedVersions` 指定するだけで行けそう
