### ISSUE TITLE
bungeecord用のprometheus exporter

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#416]
https://www.spigotmc.org/resources/bungeecord-prometheus-exporter-redisbungee-support.91924/

- waterfall対応
- redisbungee対応

なので、これで良さそう

**Comment by kory33** [comment]
これおもろい

**Comment by kory33** [comment]
Bungeecord、実はすでにJmxでJVM自体の情報露出してるんだけど、アプリケーションレベルでのメトリクスもあってよさそうだな
