### ISSUE TITLE
時々、大半のプレイヤーが一気にロビーサーバーに移動する

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#43]
頻度はあまり高くはない
特定のspigotサーバー依存というわけではなく、s1,s2などはもちろん、春やSpadeからでもなっている模様
cloudflaredが怪しい？？？

※各サーバーがcloseしたり切断されたりした時にそこにいたプレイヤーがロビーサーバーに移動するロジックはbungeecordに導入しているpluginによる挙動(bungeecordバニラの挙動は、bungeecord自体からも切断される)

**Comment by kory33** [comment]
cloudflaredのログも欲しいですね　LKEにログ基盤って乗ってましたっけ

**Comment by inductor** [comment]
ログ基盤はない

**Comment by kory33** [comment]
無い了解　悲しい

**Comment by unchama** [comment]
オンプレelasticsearchにログ流して`grafana.onp.admin.seichi.click`で見れるようにする？(bungeecordのログもみたいし)

**Comment by kory33** [comment]
まぁそれでもいいんですが、 `.onp.admin` とはみたいなところある

**Comment by inductor** [comment]
URLわけわからんくなってくるのでスーパーアプリみたいなのがほしくなってくるわね

**Comment by unchama** [comment]
これ、k8s側のパフォーマンスメトリクスも欲しいわね(今なにも取れてない)

**Comment by kory33** [comment]
Linode から全部オンプレk8sに動かしたので多分直った　しばらく様子見
