### ISSUE TITLE
`seichi-onp-network-iap`の分割

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#44]
DDoS攻撃を受けた際は基本的に上流のcloudflare等で自動的にmitigationされるが、rate limitingの設定不良などで`seichi-onp-network-iap`のVMが通信のボトルネックとなった場合は管理通信含めて全てのオンプレ向け通信が不安定となる。
このままだと障害時の調査に支障をきたすため、`seichi-onp-network-iap`の分割構築を検討する。

分割案：
- access tokenを利用している経路とそうではない経路
- dynmapな経路とそれ以外の経路
- 管理系経路とそれ以外の経路
- 分割粒度は要検討(2VM？3VM？それ以上？)

追加検討：
- 管理系webアプリケーションの認証はアプリ側でSSOを実装してもよいが、もしかするとcloudflare accessのSSOを利用するのが防衛観点では望ましそうとか思ってる(非認証ユーザートラフィックが絶対にOriginに流れないので堅牢説がある)

**Comment by kory33** [comment]
Superseded by #362
