### ISSUE TITLE
dynmap系ドメインネーミング整理

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#45]
cloudflareでページルールとかratelimitとかがかけづらい
(設定ミスると意図しないドメインに誤ってratelimitが適用されちゃったりする)

**Comment by kory33** [comment]
これ自体は一瞬で終わるんですけど、サーバー内の案内も書き換えないといけなさそう

 - WIX上のリンク
 - SeichiAssistのmap案内機能

だけ書き換えれば良さそう？

**Comment by kory33** [comment]
きたわよ
https://s1.map.gigantic.seichi.click/

あとは #436 に投げます
