### ISSUE TITLE
bungeecordに定期再起動仕込む

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#590]
36日間起動しっぱなしにしてたらいつの間にかラグの温床になってた

**Comment by kory33** [comment]
定期再起動仕込むのもそうだし、これちゃんと監視したいですね

**Comment by inductor** [comment]
https://qiita.com/k5trismegistus/items/9ad43a97a812a4e349ec アイデアは多分普通にこれで良さそう。RoleとSA作ってそれに紐づいたCronJobを作れば大丈夫

**Comment by inductor** [comment]
ScaledObjectでいいじゃん(いいじゃん)

**Comment by kory33** [comment]
KedaのScaledObjectで良さそう
