### ISSUE TITLE
マイクラサーバーの基底イメージの itzg/minecraft-server への依存を Renovate に認識させたい

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/seichi_infra#780]
これ今動いてない
https://github.com/GiganticMinecraft/seichi_infra/blob/3fcace79f1c7661ffedeb0c9848da1a5bb6dc9aa/.github/workflows/build_mcserver_base_images.yaml#L19-L24

**Comment by kory33** [comment]
これ動いていなさそう
https://github.com/GiganticMinecraft/seichi_infra/blob/f6ceac2816bea85e12569a895ac7a0facd7e3bb2/renovate.json#L17-L27

**Comment by azarashi2931** [comment]
Dockerfile の依存って Dockerfile manager https://docs.renovatebot.com/modules/manager/dockerfile/ でなんとかなりませんか？

**Comment by azarashi2931** [comment]
これって更新対象のファイルは https://github.com/GiganticMinecraft/seichi_infra/blob/main/docker-images/mcservers/base-server-image/Dockerfile で合ってますか？https://github.com/GiganticMinecraft/seichi_infra/blob/main/.github/workflows/build_mcserver_base_images.yaml ではない？

**Comment by kory33** [comment]
> これって更新対象のファイルは https://github.com/GiganticMinecraft/seichi_infra/blob/main/docker-images/mcservers/base-server-image/Dockerfile で合ってますか？https://github.com/GiganticMinecraft/seichi_infra/blob/main/.github/workflows/build_mcserver_base_images.yaml ではない？

更新対象は https://github.com/GiganticMinecraft/seichi_infra/blob/main/.github/workflows/build_mcserver_base_images.yaml の `mcserver_base_image_with_tag` の部分です（1.17 の JDK バージョンの壁をまたぐ運用をするので、二つの JDK バージョンでビルドしたく、 GitHub Workflow の matrix からイメージを指定しています）

**Comment by azarashi2931** [comment]
> "fileMatch": ["^docker-images/mcservers/base-server-image/Dockerfile$"], 

でマッチするファイルが Dockerfile の方になっているので、ここを直せば動く気がします。

**Comment by kory33** [comment]
あ～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～～

**Comment by kory33** [comment]
普通に動きました！ありがとうございます！！！！！

Fixed by [7ef70af](https://github.com/GiganticMinecraft/seichi_infra/commit/7ef70af59705841083716b6f6cc9d83eecf1bc8a).
