### ISSUE TITLE
マイクラサーバーの基底イメージへの依存を Renovate に認識させたい

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/seichi_infra#782]
各マイクラサーバーの専用イメージでの依存
https://github.com/GiganticMinecraft/seichi_infra/blob/f6ceac2816bea85e12569a895ac7a0facd7e3bb2/docker-images/mcservers/production/kagawa/Dockerfile#L1

と、その専用イメージへの StatefulSet からの依存
https://github.com/GiganticMinecraft/seichi_infra/blob/f6ceac2816bea85e12569a895ac7a0facd7e3bb2/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/stateful-set.yaml#L27

は認識してほしい（単純にPRをポチポチするだけで更新できると楽だし、PRマージをスケジュールするような運用が楽になる）

**Comment by KisaragiEffective** [comment]
https://github.com/yanorei32/uthree-ml-image/blob/master/renovate.json
で解決しそうな

**Comment by azarashi2931** [comment]
あんまり文脈を把握できてないんですが、Dockerfile manager https://docs.renovatebot.com/modules/manager/dockerfile/ と Kubernetes manager https://docs.renovatebot.com/modules/manager/kubernetes/ を普通に使う以上のことが必要な要件がある感じですか？

**Comment by kory33** [comment]
普通に使うと [dashboard](https://github.com/GiganticMinecraft/seichi_infra/issues/228#issue-1191704192) を見るとわかるようになぜか依存関係として認識してくれなくて、semver じゃないので無視されてるのかな？という仮説の元今ガチャガチャしています

**Comment by kory33** [comment]
この `packageRules` だと認識してくれなかった
https://github.com/GiganticMinecraft/seichi_infra/blob/590e1a9f03cbfae517e1916ab9ffc7d92fa56579/renovate.json#L5-L11

**Comment by azarashi2931** [comment]
あー確かに looks like a version とか言ってますね

> If the image tag in use "looks" like a version (e.g. myimage:1, myimage:1.1, myimage:1.1.0, myimage:1-onbuild) then Renovate checks the Docker registry for upgrades (e.g. from myimage:1.1.0 to myimage:1.2.0)

https://docs.renovatebot.com/docker/#how-it-works

**Comment by azarashi2931** [comment]
`packageRules` の `versioning` フィールドをゴニョればいけそうな気配を感じます

https://docs.renovatebot.com/modules/versioning/

**Comment by azarashi2931** [comment]
そういうのもあるのか〜😇 https://docs.renovatebot.com/modules/versioning/#loose-versioning

**Comment by azarashi2931** [comment]
どちらも自前のイメージなので https://docs.renovatebot.com/modules/versioning/#docker-versioning で認識できるようなタグにするのが筋良さそうに見えます。
最悪でもタグの中にソートするとリリース順になるようなバージョン的な数字が入ってるなら https://docs.renovatebot.com/modules/versioning/#regular-expression-versioning でなんとかなりそうです

**Comment by kory33** [comment]
フム～～～　なるほど…

**Comment by kory33** [comment]
イメージをビルドする Workflow に parallelism 指定して何とか連番を張るようにするしかなさそうですねぇ

**Comment by azarashi2931** [comment]
あ～あとちょっと別のアプローチとして思いついたものとして、digest pining されたイメージの更新の仕組みを利用する方法があり得ます。base image の方を例にすると、タグを `java8-jdk-e457dc9` から `java8-jdk` などの常に固定の値にして、さらに `@sha256:xxxxx` といった形でイメージの digest を指定することで、Renovate の digest pining されたイメージの更新のフローに乗せることができます。
(この方法にもイメージタグに乗ってる情報が減るという問題はありますが…)

https://docs.renovatebot.com/docker/#digest-pinning

**Comment by kory33** [comment]
なるほど！ `java8-jdk-e457dc9` と `java8-jdk` の両方のタグをつけたうえで digest pinning することでコミットの逆引きも簡単になりそうなのでこれでやってみます

**Comment by kory33** [comment]
う～～～む依存自体は認識してくれましたが digest update の PR が来ないですね

**Comment by kory33** [comment]
あ～～～更新来た OK

**Comment by kory33** [comment]
結局、 base image のタグ付け方針を変えて、 [upstreamVersion-2022.15.0-java17-jdk-4796019](https://github.com/orgs/GiganticMinecraft/packages/container/seichi_minecraft_server_base/60424465?tag=upstreamVersion-2022.15.0-java17-jdk-4796019)
[1.0.0-java17-jdk](https://github.com/orgs/GiganticMinecraft/packages/container/seichi_minecraft_server_base/60424465?tag=1.0.0-java17-jdk)
[upstreamVersion-2022.15.0-java17-jdk](https://github.com/orgs/GiganticMinecraft/packages/container/seichi_minecraft_server_base/60424465?tag=upstreamVersion-2022.15.0-java17-jdk) の様なタグにすることで解決しました　ありがとうございます！
